# zad 1
SELECT AVG(pensja) as srednia_pensja FROM EMPLOYEE;

SELECT AVG(pensja) as srednia_pensja, COUNT(*) as liczba_pracownikow from EMPLOYEE GROUP BY JOB_POSITION_ID;

SELECT YEAR(current_date()) - AVG(FLOOR(YEAR(BIRTH_DATE))) as sredni_wiek, DEPARTMENT_ID FROM EMPLOYEE GROUP BY DEPARTMENT_ID;

# zad 2
SELECT DEPARTMENT_ID, SUM(pensja) as laczna_pensja FROM EMPLOYEE GROUP BY DEPARTMENT_ID ORDER BY laczna_pensja DESC;

SELECT JOB_POSITION_ID, AVG(pensja) as srednia_pensja, COUNT(*) FROM EMPLOYEE GROUP BY JOB_POSITION_ID HAVING COUNT(*) >= 3 AND srednia_pensja > 3000;

SELECT DEPARTMENT_ID, COUNT(DISTINCT pensja) as ilosc_roznych_pensji FROM EMPLOYEE GROUP BY DEPARTMENT_ID HAVING COUNT(*) > 4 ORDER BY ilosc_roznych_pensji;

# zad 3
CREATE TABLE DEPARTMENT AS SELECT * FROM company_2025.DEPARTMENT;
CREATE TABLE JOB_POSITION AS SELECT * FROM company_2025.JOB_POSITION;

SELECT DEPARTMENT.DEPARTMENT_NAME, COUNT(*) as liczba_pracownikow FROM EMPLOYEE INNER JOIN DEPARTMENT on EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID GROUP BY DEPARTMENT_NAME;

SELECT DEPARTMENT.DEPARTMENT_NAME, GROUP_CONCAT(EMPLOYEE.FIRST_NAME, " ", EMPLOYEE.LAST_NAME) as imie_nazwisko FROM EMPLOYEE INNER JOIN DEPARTMENT on EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID GROUP BY DEPARTMENT_NAME;

# zad 4
SELECT EMPLOYEE.LAST_NAME, JOB_POSITION.POSITION_NAME FROM EMPLOYEE NATURAL JOIN JOB_POSITION WHERE YEAR(BIRTH_DATE) < 2000 AND YEAR(BIRTH_DATE) >= 1990;

SELECT EMPLOYEE.FIRST_NAME, EMPLOYEE.LAST_NAME,  JOB_POSITION.POSITION_NAME FROM EMPLOYEE NATURAL JOIN JOB_POSITION WHERE JOB_POSITION.POSITION_NAME  = "Magazynier" ORDER BY BIRTH_DATE DESC LIMIT 5;

SELECT B.SHORT_NAME, A.SHORT_NAME  FROM CLIENT A, CLIENT B WHERE A.CLIENT_ID = B.CLIENT_ID + 5;
