# zad 1
CREATE TABLE CLIENT LIKE company_2025.CLIENT;
INSERT INTO CLIENT
SELECT * FROM company_2025.CLIENT;

CREATE TABLE EMPLOYEE LIKE company_2025.EMPLOYEE;
INSERT INTO EMPLOYEE
SELECT * FROM company_2025.EMPLOYEE;

CREATE TABLE `ORDER` AS
SELECT * FROM company_2025.ORDER;



SELECT * FROM `ORDER`;
SELECT * FROM `ORDER` WHERE ORDER_STATUS = 5;

SELECT * FROM `ORDER` WHERE ORDER_STATUS IN(1, 3, 5);


# zad 2
SELECT * FROM EMPLOYEE WHERE EMPLOYEE.FIRST_NAME = "Agnieszka" AND EMPLOYEE.pensja = 3900;

SELECT * FROM EMPLOYEE WHERE EMPLOYEE.pensja BETWEEN 5000 AND 7000;

SELECT * FROM CLIENT WHERE SHORT_NAME LIKE "%eco%";

# zad 3
SELECT * FROM `ORDER` WHERE month(ORDER_DATE) BETWEEN 6 AND 7;

SELECT * FROM CLIENT WHERE TAX_IDENTIFIER IS NOT NULL ORDER BY SHORT_NAME;

SELECT * FROM company_2025.EMPLOYEE ORDER BY BIRTH_DATE LIMIT 5;