CREATE TABLE CLIENT LIKE company_2025.CLIENT;
INSERT INTO CLIENT
SELECT * FROM company_2025.CLIENT;

CREATE TABLE EMPLOYEE LIKE company_2025.EMPLOYEE;
INSERT INTO EMPLOYEE
SELECT * FROM company_2025.EMPLOYEE;

CREATE TABLE `ORDER` AS
SELECT * FROM company_2025.ORDER;



SELECT * FROM `ORDER`;
SELECT * FROM `ORDER` WHERE ORDER_STATUS = 5;

SELECT * FROM `ORDER` WHERE ORDER_STATUS IN(1, 3, 5);
