# zad 1
SELECT * FROM CLIENT c
LEFT JOIN `ORDER` o on
c.CLIENT_ID = o.CLIENT_ID
WHERE o.CLIENT_ID IS NULL;

# z podzapytaniem
SELECT c.FULL_NAME FROM CLIENT c WHERE c.CLIENT_ID
NOT IN (SELECT CLIENT_ID FROM `ORDER`);

SELECT DISTINCT UNIT_ID
FROM INVENTORY;
SELECT UNIT_ID FROM UNIT_OF_MEASUREMENT;

SELECT
uom.UNIT_NAME
FROM INVENTORY i
RIGHT JOIN UNIT_OF_MEASUREMENT uom ON uom.UNIT_ID = i.UNIT_ID
WHERE i.UNIT_ID IS NULL;


SELECT p.PRODUCT_NAME,
AVG(o.SELL_PRICE - p.PURCHASE_PRICE) AS AVG_PRICE_DIFFERENCE
FROM  PRODUCT p
JOIN ORDER_POSITION o ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY p.PRODUCT_NAME
ORDER BY AVG(o.SELL_PRICE - p.PURCHASE_PRICE) DESC;

