# zad 1
SELECT * FROM CLIENT c
LEFT JOIN `ORDER` o on
c.CLIENT_ID = o.CLIENT_ID
WHERE o.CLIENT_ID IS NULL;

# z podzapytaniem
SELECT c.FULL_NAME FROM CLIENT c WHERE c.CLIENT_ID
NOT IN (SELECT CLIENT_ID FROM `ORDER`);

SELECT DISTINCT UNIT_ID
FROM INVENTORY;
SELECT UNIT_ID FROM UNIT_OF_MEASUREMENT;

SELECT
uom.UNIT_NAME
FROM INVENTORY i
RIGHT JOIN UNIT_OF_MEASUREMENT uom ON uom.UNIT_ID = i.UNIT_ID
WHERE i.UNIT_ID IS NULL;


SELECT p.PRODUCT_NAME,
AVG(o.SELL_PRICE - p.PURCHASE_PRICE) AS AVG_PRICE_DIFFERENCE
FROM  PRODUCT p
JOIN ORDER_POSITION o ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY p.PRODUCT_NAME
ORDER BY AVG(o.SELL_PRICE - p.PURCHASE_PRICE) DESC;

# zad2
SELECT DISTINCT d.DEPARTMENT_NAME FROM `ORDER` o
INNER JOIN EMPLOYEE e ON o.EMPLOYEE_ID = e.EMPLOYEE_NAME
INNER JOIN DEPARTMENT d ON d.DEPARTMENT_ID = e.DEPARTMENT_ID;

SELECT d.DEPARTMENT_NAME, sum(op.AMOUNT) as TOTAL_ORDER_AMOUNT FROM EMPLOYEE e
INNER JOIN DEPARTMENT d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
INNER JOIN `ORDER` o ON o.EMPLOYEE_ID = e.EMPLOYEE_NAME
INNER JOIN ORDER_POSITION op ON op.ORDER_ID = o.ORDER_ID
GROUP BY d.DEPARTMENT_NAME;

SELECT d.DEPARTMENT_NAME, os.STATUS_NAME, sum(op.AMOUNT) as TOTAL_ORDER_AMOUNT 
FROM EMPLOYEE e
INNER JOIN DEPARTMENT d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
INNER JOIN `ORDER` o ON o.EMPLOYEE_ID = e.EMPLOYEE_NAME
INNER JOIN ORDER_POSITION op ON op.ORDER_ID = o.ORDER_ID
INNER JOIN ORDER_STATUS os ON o.ORDER_STATUS = os.STATUS_ID
GROUP BY d.DEPARTMENT_NAME, os.STATUS_NAME;


